#This file is an example of an environment file for defining the isolated
#networks and related parameters.
resource_registry:
  # Network Interface templates to use (these files must exist)
  #OS::TripleO::ComputeOvsDpdk::Net::SoftwareConfig: /home/stack/templates/dpdk-compute.yaml
  OS::TripleO::Compute::Net::SoftwareConfig: /home/stack/templates/dpdk-compute.yaml

  #OS::TripleO::ComputeSriov::Net::SoftwareConfig: /home/stack/templates/sriov-compute.yaml
  OS::TripleO::Controller::Net::SoftwareConfig: /home/stack/templates/controller.yaml

  OS::TripleO::Services::ComputeNeutronOvsDpdkAgent: /usr/share/openstack-tripleo-heat-templates/puppet/services/neutron-ovs-dpdk-agent.yaml
  #OS::TripleO::Services::NeutronSriovAgent: /usr/share/openstack-tripleo-heat-templates/puppet/services/neutron-sriov-agent.yaml

  # Ceph storage nodes configs.
  #OS::TripleO::CephStorage::Net::SoftwareConfig: /home/stack/templates/ceph-storage.yaml

  OS::TripleO::NodeUserData: /home/stack/templates/first-boot.yaml
  OS::TripleO::NodeExtraConfigPost: /home/stack/templates/post-install.yaml

parameter_defaults:
  # This section is where deployment-specific configuration is done
  # CIDR subnet mask length for provisioning network
  ControlPlaneSubnetCidr: '24'
  # Gateway router for the provisioning network (or Undercloud IP)
  ControlPlaneDefaultRoute: 192.168.77.77
  ControlPlaneIp: 192.168.77.77
  EC2MetadataIp: 192.168.77.77 # Generally the IP of the Undercloud
  # Customize the IP subnets to match the local environment
  #ExternalIpSubnet: 10.19.108.0/24
  #ExternalInterfaceDefaultRoute: 10.19.108.254
  #InternalApiIpSubnet: 10.1.1.0/24
  #InternalApiDefaultRoute: 10.1.1.254
  #StorageIpSubnet: 10.1.2.0/24
  #TenantIpSubnet: 10.1.4.0/24
  #StorageMgmtIpSubnet: 10.1.3.0/24

  InternalApiNetCidr: 10.1.1.0/24
  StorageNetCidr: 10.1.2.0/24
  StorageMgmtNetCidr: 10.1.3.0/24
  TenantNetCidr: 10.1.4.0/24
  ExternalNetCidr: 10.19.108.0/24
  # Customize the VLAN IDs to match the local environment
  InternalApiNetworkVlanID: 1020
  StorageNetworkVlanID: 1030
  StorageMgmtNetworkVlanID: 1040
  TenantNetworkVlanID: 1050
  ExternalNetworkVlanID: 100
  # Customize the IP ranges on each network to use for static IPs and VIPs
  InternalApiAllocationPools: [{'start': '10.1.1.1', 'end': '10.1.1.253'}]
  StorageAllocationPools: [{'start': '10.1.2.1', 'end': '10.1.2.253'}]
  StorageMgmtAllocationPools: [{'start': '10.1.3.1', 'end': '10.1.3.253'}]
  TenantAllocationPools: [{'start': '10.1.4.1', 'end': '10.1.4.253'}]
  # Leave room if the external network is also used for floating IPs
  ExternalAllocationPools: [{'start': '10.19.108.23', 'end': '10.19.108.50'}]
  ExternalNetworkVip: 10.19.108.51

# Specify the NTP server for nodes to use
  NtpServer: 10.5.26.10
# Customize the IP ranges on each network to use for static IPs and VIPs

  # Global MTU configuration on Neutron
#  NeutronGlobalPhysnetMtu: 1500

  NeutronMechanismDrivers: "openvswitch,sriovnicswitch"

  # Gateway router for the external network
  ExternalInterfaceDefaultRoute: 10.19.108.254


  # Uncomnent if using the Management Network (see network-management.yaml)
  # ManagementNetCidr: 10.0.1.0/24
  # ManagementAllocationPools: [{'start': '10.0.1.10', 'end', '10.0.1.50'}]
  # Use either this parameter or ControlPlaneDefaultRoute in the NIC templates
  # ManagementInterfaceDefaultRoute: 10.0.1.1
  # Define the DNS servers (maximum 2) for the overcloud nodes
  DnsServers: ["8.8.8.8","8.8.4.4"]

  # Set to empty string to enable multiple external networks or VLANs
  NeutronExternalNetworkBridge: "''"

  # Customize bonding options, e.g. "mode=4 lacp_rate=1 updelay=1000 miimon=100"
  # LinuxBondInterfaceOptions: "mode=802.3ad" <== Don't use this use next one specifying details to make it faster
  LinuxBondInterfaceOptions: "mode=4 lacp_rate=1 updelay=0 miimon=100"


 # Flavor of controller and compute nodes:
 # OvercloudComputeSriovFlavor: computesriov
  OvercloudControlFlavor: control
  OvercloudComputeOvsDpdkFlavor: compute
  #OvercloudCephStorageFlavor: ceph-storage
  
 # Number of nodes to deploy.
#  ControllerCount: 1
#  ComputeSriovCount: 0
#  CephStorageCount: 0
#  ComputeOvsDpdkCount: 2

  ##################################
  # Common performance paramenters
  ##################################

  ComputeKernelArgs: "iommu=pt intel_iommu=on default_hugepagesz=1GB hugepagesz=1G hugepages=12"

  NovaSchedulerAvailableFilters: ["nova.scheduler.filters.all_filters","nova.scheduler.filters.pci_passthrough_filter.PciPassthroughFilter"]

  NovaSchedulerDefaultFilters: ['AvailabilityZoneFilter','RamFilter','ComputeFilter','ComputeCapabilitiesFilter','ImagePropertiesFilter','ServerGroupAntiAffinityFilter','ServerGroupAffinityFilter','PciPassthroughFilter','NUMATopologyFilter']

#  NovaSchedulerAvailableFilters: ["nova.scheduler.filters.all_filters","nova.scheduler.filters.pci_passthrough_filter.PciPassthroughFilter","nova.scheduler.filters.numa_topology_filter.NUMATopologyFilter","nova.scheduler.filters.aggregate_instance_extra_specs.AggregateInstanceExtraSpecsFilter"]

#  NovaSchedulerDefaultFilters: ['AvailabilityZoneFilter','RamFilter','ComputeFilter','ComputeCapabilitiesFilter','ImagePropertiesFilter','ServerGroupAntiAffinityFilter','ServerGroupAffinityFilter', 'PciPassthroughFilter', 'NUMATopologyFilter', 'AggregateInstanceExtraSpecsFilter']


  # Add a list or range of physical CPU cores to be reserved for virtual machine processes
  #NovaVcpuPinSet: ['4-11','24-35','16-23','36-47']
  NovaVcpuPinSet: ['16-23','36-47']
 
  # Set the tunnel type for tenant network (for example, vxlan or gre). To disable the tunnel type parameter, set the value to ""
  NeutronTunnelTypes: "vxlan"
 
  # Set the tenant network type for OpenStack Networking. The options available are vlan or vxlan:
  NeutronNetworkType: 'vxlan'
 
  # Network VLAN ranges for both SRIOV and DPDK:
#  NeutronNetworkVLANRanges: 'datacentre:2000:2070,phy-sriov1:2072:2093,phy-sriov2:2072:2093'

  # Neutron Bridge Mappings for both SRIOV and DPDK networks:
#  NeutronBridgeMappings: 'datacentre:br-ex,phy-sriov1:br-isolated1,phy-sriov2:br-isolated2'

  # Set the Open vSwitch logical to physical bridge mappings:
  NeutronBridgeMappings: 'datacentre:br-ex_Haresh,dpdk:br-Haresh_dpdk'

  # Set the OpenStack Networking ML2 and Open vSwitch VLAN mapping range:
  NeutronNetworkVLANRanges: 'datacentre:100:100,dpdk:2073:2073'

  ##########################
  # OVS DPDK configuration #
  ##########################

  ## NeutronDpdkCoreList and NeutronDpdkMemoryChannels are REQUIRED settings.
  ## Attempting to deploy DPDK without appropriate values will cause deployment to fail or lead to unstable deployments.

  # For OVS-DPDK-BONDs
  DpdkBondInterfaceOvsOptions: "bond_mode=balance-tcp lacp=active"

  #BondInterfaceOvsOptions: "bond_mode=balance-slb lacp=active"

  # List of cores to be used for DPDK Poll Mode Driver
  NeutronDpdkCoreList: "'12,13,14,15'"

  # NeutronDpdkSocketMemory
  NeutronDpdkSocketMemory: "'1024,1024'"

  # NeutronDpdkDriverType
  NeutronDpdkDriverType: "vfio-pci"

  # Number of memory channels to be used for DPDK
  NeutronDpdkMemoryChannels: "4"

  # Datapath type for ovs bridges
  NeutronDatapathType: "netdev"

  # The vhost-user socket directory for OVS
  NeutronVhostuserSocketDir: "/var/run/openvswitch"

  # Reserve the RAM for the host processes
  NovaReservedHostMemory: "4096"

  # Set a list or range of physical CPU cores that should be excluded from tuning:
  HostCpusList: "0,1,2,3,4,5,6,7,8,9,10,11,24,25,26,27,28,29,30,31,32,33,34,35"

  # HostIsolatedCoreList = NeutronDpdkCoreList(12-15) + NovaVcpuPinSet(16-23)
  #HostIsolatedCoreList: "12-23"
  HostIsolatedCoreList: ['12-23','36-47']
 ########################
 # SR-IOV configuration #
 ######################## 

# NeutronMechanismDrivers: "openvswitch,sriovnicswitch"

#  NovaPCIPassthrough: 
#    - devname: "ens6f0"
#      physical_network: "phy-sriov1"
#    - devname: "ens6f1"
#      physical_network: "phy-sriov2"


#  NeutronSupportedPCIVendorDevs: ['8086:1515']
#  NeutronPhysicalDevMappings: "phy-sriov1:ens6f0,phy-sriov2:ens6f1"
#  NeutronSriovNumVFs: "ens6f0:5,ens6f1:5"

  #BondInterfaceOvsOptions: "bond_mode=balance-slb lacp=active"
